# Generated by Django 5.1.1 on 2024-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
